CREATE TABLE Car.Car
(
	CarID INT NOT NULL  IDENTITY(1,1),
	ModelID INT NOT NULL,
	RegistrationNumber VARCHAR(12) NOT NULL,
	MOTExpirey DATETIME2 NOT NULL,
	VinNumber VARCHAR(30) NOT NULL,
	CurrentMilage INT NOT NULL,
	ColourID INT NOT NULL,
	PersonID INT NOT NULL,
	CONSTRAINT PK_Car_CarID PRIMARY KEY (CarID),
	CONSTRAINT FK_Car_PersonID FOREIGN KEY (PersonID) REFERENCES Person.Person (PersonID),
	CONSTRAINT FK_Car_ModelID FOREIGN KEY (ModelID) REFERENCES Car.Model (ModelID),
	CONSTRAINT FK_Car_ColourID FOREIGN KEY (ColourID) REFERENCES Car.Colour (ColourID)
)
