CREATE TABLE Person.Person
(
	PersonID INT NOT NULL IDENTITY(1,1),
	Title VARCHAR(5) NOT NULL,
	FirstName VARCHAR(30)  NOT NULL,
	Surname VARCHAR(50) NOT NULL,
	MobileNo VARCHAR(25) NULL,
	HouseNo VARCHAR(25) NULL,
	PersonType CHAR(2) NOT NULL,
	EntryDate DATETIME2 NOT NULL CONSTRAINT DF_Person_EntryDate DEFAULT GETDATE() 
	CONSTRAINT PK_Person_PersonID PRIMARY KEY (PersonID)
)
